import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest';
import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';

// This hook is on the critical path of every tool call, so it may never reach for a model. Making
// `buildEngine` throw turns that into a test that fails loudly rather than one that inspects mocks.
vi.mock('../../supervisor/factory', () => ({
  buildEngine: () => { throw new Error('PreToolUse must never call a model'); },
}));

import { PreToolUseOutput, decideBlock, handle } from '../../hooks/preToolUse';
import * as permissionRequest from '../../hooks/permissionRequest';
import { parsePractices } from '../../policy/practices';
import * as io from '../../hooks/io';
import { HookInput } from '../../hooks/io';
import { DecisionRecord, readJsonl } from '../../audit/trail';
import { decisionsPath } from '../../hooks/paths';

const PRACTICES = `
### Intention: Secrets are never read into the transcript

| Field | Value |
|---|---|
| id | team-sec-003 |
| level | red |

Match: \`/\\.env\\b/\`, AWS_SECRET

A credential in the transcript is a credential in every log that transcript reaches.

---

### Intention: Clearing the build directory is routine

| Field | Value |
|---|---|
| id | build-is-disposable |
| level | green |

Match: rm -rf ./build

It is regenerated by every build, so deleting it destroys nothing.
`;

const clauses = parsePractices(PRACTICES, 'team');

const call = (tool: string, input: Record<string, unknown>) => ({
  session_id: 'sess-1',
  cwd: '/tmp/repo',
  hook_event_name: 'PreToolUse',
  tool_name: tool,
  tool_input: input,
});

const reasonOf = (output: unknown): string =>
  (output as PreToolUseOutput).hookSpecificOutput.permissionDecisionReason;

let dir: string;
let practicesFile: string;
const saved = { ...process.env };

beforeEach(() => {
  dir = fs.mkdtempSync(path.join(os.tmpdir(), 'ss-pretool-'));
  practicesFile = path.join(dir, 'practices.md');
  fs.writeFileSync(practicesFile, PRACTICES, 'utf8');
  process.env.SESSION_SITTER_DATA_DIR = dir;
  process.env.SESSION_SITTER_PRACTICES = practicesFile;
  delete process.env.SESSION_SITTER_PRETOOL;
});

afterEach(() => {
  process.env = { ...saved };
  fs.rmSync(dir, { recursive: true, force: true });
  vi.restoreAllMocks();
});

const records = (): DecisionRecord[] => readJsonl<DecisionRecord>(decisionsPath());

describe('decideBlock — the only two things that deny', () => {
  it('denies a shell command that reads a file a red clause forbids, citing the clause', () => {
    const block = decideBlock(call('Bash', { command: 'cat .env' }), clauses);
    expect(block?.clause).toBe('practices §team-sec-003');
    expect(block?.actor).toBe('policy');
  });

  it('denies every other route to the same file, not just Bash', () => {
    // The hole the live run left open: after the Bash route was denied, nothing structurally
    // stopped a second attempt through Read.
    for (const input of [
      call('Read', { file_path: '/tmp/repo/.env' }),
      call('Grep', { pattern: 'AWS_SECRET', path: '.' }),
      call('Glob', { pattern: '**/.env' }),
      call('NotebookRead', { notebook_path: '/tmp/repo/.env' }),
      call('Write', { file_path: '/tmp/repo/.env', content: 'x' }),
      call('Edit', { file_path: '/tmp/repo/.env', old_string: 'a', new_string: 'b' }),
    ]) {
      expect(decideBlock(input, clauses)?.clause, input.tool_name).toBe('practices §team-sec-003');
    }
  });

  it('denies on the built-in destructive table when nothing is written', () => {
    const block = decideBlock(call('Bash', { command: 'rm -rf /tmp/repo/src' }), []);
    expect(block?.actor).toBe('deterministic');
    expect(block?.clause).toBeNull();
  });

  it('returns no decision for an ordinary call', () => {
    expect(decideBlock(call('Read', { file_path: '/tmp/repo/src/index.ts' }), clauses)).toBeNull();
    expect(decideBlock(call('Bash', { command: 'npm test' }), clauses)).toBeNull();
    expect(decideBlock(call('Bash', { command: 'ls -la' }), clauses)).toBeNull();
    expect(decideBlock(call('Grep', { pattern: 'loadSettings' }), clauses)).toBeNull();
  });

  it('lets a written green clause override the built-in table', () => {
    expect(decideBlock(call('Bash', { command: 'rm -rf ./build' }), clauses)).toBeNull();
  });

  it('leaves a correctable call to the correction lane rather than denying it', () => {
    // `git push --force` is in the built-in destructive table AND has a correction rule. Denying it
    // here would kill the rewrite, so this hook must stand aside.
    expect(decideBlock(call('Bash', { command: 'git push --force origin main' }), [])).toBeNull();
  });
});

describe('handle', () => {
  it('returns a PreToolUse deny and records one audit entry', async () => {
    const output = await handle(call('Read', { file_path: '/tmp/repo/.env' }));
    expect((output as PreToolUseOutput).hookSpecificOutput.hookEventName).toBe('PreToolUse');
    expect((output as PreToolUseOutput).hookSpecificOutput.permissionDecision).toBe('deny');
    expect(reasonOf(output)).toContain('practices §team-sec-003');

    const written = records();
    expect(written).toHaveLength(1);
    expect(written[0]).toMatchObject({
      tool: 'Read', decision: 'deny', clause: 'practices §team-sec-003', actor: 'policy',
    });
    expect(written[0].note).toContain('PreToolUse');
  });

  it('records nothing at all for a no-decision, so the trail is not one line per tool call', async () => {
    expect(await handle(call('Read', { file_path: '/tmp/repo/src/index.ts' }))).toEqual({});
    expect(await handle(call('Bash', { command: 'npm test' }))).toEqual({});
    expect(records()).toHaveLength(0);
  });

  it('is off when SESSION_SITTER_PRETOOL is off, and on by default', async () => {
    process.env.SESSION_SITTER_PRETOOL = 'off';
    expect(await handle(call('Read', { file_path: '/tmp/repo/.env' }))).toEqual({});
    delete process.env.SESSION_SITTER_PRETOOL;
    expect(await handle(call('Read', { file_path: '/tmp/repo/.env' }))).not.toEqual({});
  });

  it('never denies AskUserQuestion, whatever the question says', async () => {
    expect(await handle(call('AskUserQuestion', { question: 'should I read .env?' }))).toEqual({});
  });

  it('returns no decision — never a block — when the practices cannot be read', async () => {
    process.env.SESSION_SITTER_PRACTICES = path.join(dir, 'missing.md');
    expect(await handle(call('Bash', { command: 'cat .env' }))).toEqual({});
  });

  it('returns no decision when the clause loader throws', async () => {
    const spy = vi.spyOn(permissionRequest, 'loadClauses').mockRejectedValue(new Error('boom'));
    expect(await handle(call('Bash', { command: 'cat .env' }))).toEqual({});
    expect(spy).toHaveBeenCalled();
  });

  it('lets a thrown error out of handle as a no-decision, never a block', async () => {
    // `runHook` is registered with no `fallback`, so it prints `{}` for anything `handle` throws.
    // Proving that at the process boundary: a circular tool input makes the haystack throw.
    const circular: Record<string, unknown> = {};
    circular.self = circular;
    await expect(handle(call('Bash', circular))).rejects.toThrow();

    const printed: string[] = [];
    vi.spyOn(io, 'readStdin').mockResolvedValue(JSON.stringify(call('Bash', { command: 'cat .env' })));
    vi.spyOn(process.stdout, 'write').mockImplementation(text => { printed.push(String(text)); return true; });
    vi.spyOn(process, 'exit').mockImplementation((() => undefined) as never);
    vi.spyOn(permissionRequest, 'loadClauses').mockRejectedValue(new Error('boom'));
    await io.runHook(handle as (i: HookInput) => Promise<unknown>);
    expect(printed.join('')).toBe('{}\n');
  });
});
